#put commeffort and accumulated value function in one figure
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/NormalandDiffCommEffortvscellsize,4cars.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/commEffort4Cars1Page.pdf

#put all closed-loop costs for different cell sizes (0.5-2) into one figure
#pdfjam --nup 2x2 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{10cm,8cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCosts4cars,Neq12,Cellsize0,5.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCosts4cars,Neq12,Cellsize1.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCosts4cars,Neq12,Cellsize1,5.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCosts4cars,Neq12,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/closedLoopCosts4On1Page.pdf

#put all open-loop costs for different cell sizes (0.5-2) into one figure
#pdfjam --nup 2x2 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{10cm,8cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/openLoopCosts4cars,Neq12,Cellsize0,5.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/openLoopCosts4cars,Neq12,Cellsize1.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/openLoopCosts4cars,Neq12,Cellsize1,5.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/openLoopCosts4cars,Neq12,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/openLoopCosts4On1Page.pdf

#put all closed-loop culm. costs and one cost example into one figure
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopAccumCostsover4cars,Neq12.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCosts4cars,Neq12,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/closedLoopCulmCostsAnd4Cars.pdf

#put all open-loop culm. costs and one cost example into one figure
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/openLoopAccumCostsover4cars,Neq12.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/openLoopCosts4cars,Neq12,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/openLoopCulmCostsAnd4Cars.pdf

#trajectory figure
#pdfjam --nup 2x2 --frame false --noautoscale false --delta "0.1cm 0.1cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/simTrajec/1.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/simTrajec/2.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/simTrajec/3.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/simTrajec/4.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/holonomTrajec.pdf

#min priority without memory
#put all open-loop culm. costs and one cost example into one figure (min Priority)
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHOUTMEM/closedLoopAccumCostsover4cars,Neq13.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHOUTMEM/closedLoopCosts4cars,Neq13,Cellsize1.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithoutMemOpenLoop/closedLoopCulmCostsAnd4CarsMinOpenLoopCostsPrio.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHOUTMEM/openLoopAccumCostsover4cars,Neq13.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHOUTMEM/openLoopCosts4cars,Neq13,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithoutMemOpenLoop/openLoopCulmCostsAnd4CarsMinOpenLoopCostsPrio.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHOUTMEM/NormalandDiffCommEffortvscellsize,4cars.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHOUTMEM/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithoutMemOpenLoop/commEffort4Cars1Page.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHOUTMEM/closedLoopAccumCostsover4cars,Neq9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHOUTMEM/closedLoopCosts4cars,Neq9,Cellsize1,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithoutMemClosedLoop/closedLoopCulmCostsAnd4CarsMinClosedLoopCostsPrio.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHOUTMEM/openLoopAccumCostsover4cars,Neq9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHOUTMEM/openLoopCosts4cars,Neq9,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithoutMemClosedLoop/openLoopCulmCostsAnd4CarsMinClosedLoopCostsPrio.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHOUTMEM/NormalandDiffCommEffortvscellsize,4cars.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHOUTMEM/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithoutMemClosedLoop/commEffort4Cars1Page.pdf

#min priority with memory (min openloop-priority)

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/closedLoopAccumCostsover4cars,Neq9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/closedLoopCosts4cars,Neq9,Cellsize0,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemOpenLoop/closedLoopCulmCostsAnd4CarsMinOpenLoopCostsPrioWithMemory.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/openLoopAccumCostsover4cars,Neq9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/openLoopCosts4cars,Neq9,Cellsize0,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemOpenLoop/openLoopCulmCostsAnd4CarsMinOpenLoopCostsPrioWithMemory.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/MaxPriorityQueues,minopenloopcostswithmemory,4cars,Neq,9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/NumberOfPriorityQueues,minopenloopcostswithmemory,4cars,Neq9.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemOpenLoop/priorityQueues4CarsMinOpenLoopCostsPrioWithMemory.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/NormalandDiffCommEffortvscellsize,4cars.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYOPENLOOPWTIHMEM/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemOpenLoop/commEffort4Cars1Page.pdf



#min priority with memory (min closedloop-priority)

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/closedLoopAccumCostsover4cars,Neq9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/closedLoopCosts4cars,Neq9,Cellsize0,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemClosedLoop/closedLoopCulmCostsAnd4CarsMinClosedLoopCostsPrioWithMemory.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/openLoopAccumCostsover4cars,Neq9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/openLoopCosts4cars,Neq9,Cellsize0,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemClosedLoop/openLoopCulmCostsAnd4CarsMinClosedLoopCostsPrioWithMemory.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/MaxPriorityQueues,minclosedloopcostswithmemory,4cars,Neq,9.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/NumberOfPriorityQueues,minclosedloopcostswithmemory,4cars,Neq9.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemClosedLoop/priorityQueues4CarsMinClosedLoopCostsPrioWithMemory.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/NormalandDiffCommEffortvscellsize,4cars.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop_Qt_5_11_1_GCC_64bit-Release/PRIORITYCLOSEDLOOPWITHMEM/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityWithMemClosedLoop/commEffort4Cars1Page.pdf


#put all closed-loop culm. costs and one cost example into one figure (interval moving)
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopAccumCostsover3cars,Neq8.pdf ~/Dokumente/simulator/build-simulation_intersection_scenario-Desktop-Release/closedLoopCosts3cars,Neq8,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/closedLoopCulmCostsAnd3CarsMovingIntervals.pdf

#priority hierarchy (min open-loop priority costs)
pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/closedLoopAccumCostsover4cars,Neq9.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/closedLoopCosts4cars,Neq9,Cellsize1,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/closedLoopCulmCostsAnd4CarsMinOpenLoopCostsPrioWithMemoryHierarchy.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/openLoopAccumCostsover4cars,Neq9.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/openLoopCosts4cars,Neq9,Cellsize1,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/openLoopCulmCostsAnd4CarsMinOpenLoopCostsPrioWithMemoryHierarchy.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/MaxPriorityQueues,minopenloopcostswithmemoryhierarchy,4cars,Neq,9.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/NumberOfPriorityQueues,minopenloopcostswithmemoryhierarchy,4cars,Neq9.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/priorityQueues4CarsMinOpenLoopCostsPrioWithMemoryHierarchy.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/NormalandDiffCommEffortvscellsize,4cars.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinOpenLoop/commEffort4Cars1Page.pdf

#priority hierarchy (min closed-loop priority costs)
pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/closedLoopAccumCostsover4cars,Neq9.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/closedLoopCosts4cars,Neq9,Cellsize1.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/closedLoopCulmCostsAnd4CarsMinClosedLoopCostsPrioWithMemoryHierarchy.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/openLoopAccumCostsover4cars,Neq9.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/openLoopCosts4cars,Neq9,Cellsize1,5.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/openLoopCulmCostsAnd4CarsMinClosedLoopCostsPrioWithMemoryHierarchy.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/MaxPriorityQueues,minclosedloopcostswithmemoryhierarchy,4cars,Neq,9.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/NumberOfPriorityQueues,minclosedloopcostswithmemoryhierarchy,4cars,Neq9.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/priorityQueues4CarsMinClosedLoopCostsPrioWithMemoryHierarchy.pdf

pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/NormalandDiffCommEffortvscellsize,4cars.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/closedLoopCostsvscellsize.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityHierarchyMinClosedLoop/commEffort4Cars1Page.pdf


#priority tree (min open loop priority costs)
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/closedLoopAccumCostsover4cars,Neq4.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/closedLoopCosts4cars,Neq4,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/closedLoopCulmCostsAnd4CarsMinOpenLoopCostsPrioWithTree.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/openLoopAccumCostsover4cars,Neq4.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/openLoopCosts4cars,Neq4,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/openLoopCulmCostsAnd4CarsMinOpenLoopCostsPrioWithTree.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/MaxPriorityQueues,minopenloopcostswithmemorytree,4cars,Neq,4.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/NumberOfPriorityQueues,minopenloopcostswithmemorytree,4cars,Neq4.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinOpenLoop/priorityQueues4CarsMinOpenLoopCostsPrioWithTree.pdf

#priority tree (min closed loop priority costs)
#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/closedLoopAccumCostsover4cars,Neq4.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/closedLoopCosts4cars,Neq4,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/closedLoopCulmCostsAnd4CarsMinClosedLoopCostsPrioWithTree.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/openLoopAccumCostsover4cars,Neq4.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/openLoopCosts4cars,Neq4,Cellsize2.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/openLoopCulmCostsAnd4CarsMinClosedLoopCostsPrioWithTree.pdf

#pdfjam --nup 2x1 --frame false --noautoscale false --delta "0.2cm 0.3cm" --scale 1 --papersize '{8cm,4cm}' /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/MaxPriorityQueues,minclosedloopcostswithmemorytree,4cars,Neq,4.pdf /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/NumberOfPriorityQueues,minclosedloopcostswithmemorytree,4cars,Neq4.pdf --outfile /media/truecrypt1/Doktorarbeit/Collaborations/Mohamed/gridmpc/images/priorityQueuesMinClosedLoop/priorityQueues4CarsMinClosedLoopCostsPrioWithTree.pdf
