/*// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef PROTOBUF_messages_2eproto__INCLUDED
#define PROTOBUF_messages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace CarComm {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_messages_2eproto();
void protobuf_AssignDesc_messages_2eproto();
void protobuf_ShutdownFile_messages_2eproto();

class Cell;

// ===================================================================

class Cell : public ::google::protobuf::Message {
 public:
  Cell();
  virtual ~Cell();

  Cell(const Cell& from);

  inline Cell& operator=(const Cell& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Cell& default_instance();

  void Swap(Cell* other);

  // implements Message ----------------------------------------------

  inline Cell* New() const { return New(NULL); }

  Cell* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Cell& from);
  void MergeFrom(const Cell& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Cell* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string car = 1;
  void clear_car();
  static const int kCarFieldNumber = 1;
  const ::std::string& car() const;
  void set_car(const ::std::string& value);
  void set_car(const char* value);
  void set_car(const char* value, size_t size);
  ::std::string* mutable_car();
  ::std::string* release_car();
  void set_allocated_car(::std::string* car);

  // optional uint32 k = 2;
  void clear_k();
  static const int kKFieldNumber = 2;
  ::google::protobuf::uint32 k() const;
  void set_k(::google::protobuf::uint32 value);

  // optional uint32 m = 3;
  void clear_m();
  static const int kMFieldNumber = 3;
  ::google::protobuf::uint32 m() const;
  void set_m(::google::protobuf::uint32 value);

  // optional double t = 4;
  void clear_t();
  static const int kTFieldNumber = 4;
  double t() const;
  void set_t(double value);

  // optional uint32 kTarget = 5;
  void clear_ktarget();
  static const int kKTargetFieldNumber = 5;
  ::google::protobuf::uint32 ktarget() const;
  void set_ktarget(::google::protobuf::uint32 value);

  // optional uint32 mTarget = 6;
  void clear_mtarget();
  static const int kMTargetFieldNumber = 6;
  ::google::protobuf::uint32 mtarget() const;
  void set_mtarget(::google::protobuf::uint32 value);

  // optional int32 globalLiveTime = 7;
  void clear_globallivetime();
  static const int kGlobalLiveTimeFieldNumber = 7;
  ::google::protobuf::int32 globallivetime() const;
  void set_globallivetime(::google::protobuf::int32 value);

  // optional int32 globalWaitTime = 8;
  void clear_globalwaittime();
  static const int kGlobalWaitTimeFieldNumber = 8;
  ::google::protobuf::int32 globalwaittime() const;
  void set_globalwaittime(::google::protobuf::int32 value);

  // optional int32 reserveRequestsNextCell = 9;
  void clear_reserverequestsnextcell();
  static const int kReserveRequestsNextCellFieldNumber = 9;
  ::google::protobuf::int32 reserverequestsnextcell() const;
  void set_reserverequestsnextcell(::google::protobuf::int32 value);

  // optional int32 waitTimeNextCell = 10;
  void clear_waittimenextcell();
  static const int kWaitTimeNextCellFieldNumber = 10;
  ::google::protobuf::int32 waittimenextcell() const;
  void set_waittimenextcell(::google::protobuf::int32 value);

  // optional int32 externalRequests = 11;
  void clear_externalrequests();
  static const int kExternalRequestsFieldNumber = 11;
  ::google::protobuf::int32 externalrequests() const;
  void set_externalrequests(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CarComm.Cell)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr car_;
  ::google::protobuf::uint32 k_;
  ::google::protobuf::uint32 m_;
  double t_;
  ::google::protobuf::uint32 ktarget_;
  ::google::protobuf::uint32 mtarget_;
  ::google::protobuf::int32 globallivetime_;
  ::google::protobuf::int32 globalwaittime_;
  ::google::protobuf::int32 reserverequestsnextcell_;
  ::google::protobuf::int32 waittimenextcell_;
  ::google::protobuf::int32 externalrequests_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static Cell* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Cell

// optional string car = 1;
inline void Cell::clear_car() {
  car_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Cell::car() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.car)
  return car_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Cell::set_car(const ::std::string& value) {
  
  car_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CarComm.Cell.car)
}
inline void Cell::set_car(const char* value) {
  
  car_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CarComm.Cell.car)
}
inline void Cell::set_car(const char* value, size_t size) {
  
  car_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CarComm.Cell.car)
}
inline ::std::string* Cell::mutable_car() {
  
  // @@protoc_insertion_point(field_mutable:CarComm.Cell.car)
  return car_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Cell::release_car() {
  
  return car_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Cell::set_allocated_car(::std::string* car) {
  if (car != NULL) {
    
  } else {
    
  }
  car_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), car);
  // @@protoc_insertion_point(field_set_allocated:CarComm.Cell.car)
}

// optional uint32 k = 2;
inline void Cell::clear_k() {
  k_ = 0u;
}
inline ::google::protobuf::uint32 Cell::k() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.k)
  return k_;
}
inline void Cell::set_k(::google::protobuf::uint32 value) {
  
  k_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.k)
}

// optional uint32 m = 3;
inline void Cell::clear_m() {
  m_ = 0u;
}
inline ::google::protobuf::uint32 Cell::m() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.m)
  return m_;
}
inline void Cell::set_m(::google::protobuf::uint32 value) {
  
  m_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.m)
}

// optional double t = 4;
inline void Cell::clear_t() {
  t_ = 0;
}
inline double Cell::t() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.t)
  return t_;
}
inline void Cell::set_t(double value) {
  
  t_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.t)
}

// optional uint32 kTarget = 5;
inline void Cell::clear_ktarget() {
  ktarget_ = 0u;
}
inline ::google::protobuf::uint32 Cell::ktarget() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.kTarget)
  return ktarget_;
}
inline void Cell::set_ktarget(::google::protobuf::uint32 value) {
  
  ktarget_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.kTarget)
}

// optional uint32 mTarget = 6;
inline void Cell::clear_mtarget() {
  mtarget_ = 0u;
}
inline ::google::protobuf::uint32 Cell::mtarget() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.mTarget)
  return mtarget_;
}
inline void Cell::set_mtarget(::google::protobuf::uint32 value) {
  
  mtarget_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.mTarget)
}

// optional int32 globalLiveTime = 7;
inline void Cell::clear_globallivetime() {
  globallivetime_ = 0;
}
inline ::google::protobuf::int32 Cell::globallivetime() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.globalLiveTime)
  return globallivetime_;
}
inline void Cell::set_globallivetime(::google::protobuf::int32 value) {
  
  globallivetime_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.globalLiveTime)
}

// optional int32 globalWaitTime = 8;
inline void Cell::clear_globalwaittime() {
  globalwaittime_ = 0;
}
inline ::google::protobuf::int32 Cell::globalwaittime() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.globalWaitTime)
  return globalwaittime_;
}
inline void Cell::set_globalwaittime(::google::protobuf::int32 value) {
  
  globalwaittime_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.globalWaitTime)
}

// optional int32 reserveRequestsNextCell = 9;
inline void Cell::clear_reserverequestsnextcell() {
  reserverequestsnextcell_ = 0;
}
inline ::google::protobuf::int32 Cell::reserverequestsnextcell() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.reserveRequestsNextCell)
  return reserverequestsnextcell_;
}
inline void Cell::set_reserverequestsnextcell(::google::protobuf::int32 value) {
  
  reserverequestsnextcell_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.reserveRequestsNextCell)
}

// optional int32 waitTimeNextCell = 10;
inline void Cell::clear_waittimenextcell() {
  waittimenextcell_ = 0;
}
inline ::google::protobuf::int32 Cell::waittimenextcell() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.waitTimeNextCell)
  return waittimenextcell_;
}
inline void Cell::set_waittimenextcell(::google::protobuf::int32 value) {
  
  waittimenextcell_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.waitTimeNextCell)
}

// optional int32 externalRequests = 11;
inline void Cell::clear_externalrequests() {
  externalrequests_ = 0;
}
inline ::google::protobuf::int32 Cell::externalrequests() const {
  // @@protoc_insertion_point(field_get:CarComm.Cell.externalRequests)
  return externalrequests_;
}
inline void Cell::set_externalrequests(::google::protobuf::int32 value) {
  
  externalrequests_ = value;
  // @@protoc_insertion_point(field_set:CarComm.Cell.externalRequests)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace CarComm

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_2eproto__INCLUDED
*/
